### PR TITLE
ddcutil support for external display brightness control

### PR DESCRIPTION
**Pull request by az01101001**
add `ddcutil` in addition to `light` and `brightnessctl` to allow controlling brightness for external monitors

### CODE REVIEW

**Comment by az01101001** [comment]
last commit should say `combobox` instead of `checkbox`, sorry

**Comment by nwg-piotr** [comment]
Seems to work well, but we'll need to update Wiki, as it's not easy to set up ddcutils. I mean especially this: https://www.ddcutil.com/i2c_permissions

I'll need a 6-pack to update Wiki, as all the pictures are gone since the old server died. :/

**Comment by nwg-piotr** [comment]
More general note: on my triple-headed setup (laptop + 2 external displays) I need to add 2 more `Controls` instances just to have a brightness slider for each output. This increases CPU usage significantly, and I personally wouldn't use it. Maybe we could have a separate slider for each output in a single Controls window?

**Comment by az01101001** [comment]
A separate module just for `ddcutil`? Or for brightness control in general?

**Comment by nwg-piotr** [comment]
Yeah, it could be a `BrightnessSlider` module as well. Just a brightness icon in the panel widget (optionally with the percentage), and a window w/ a slider on `GtkLayerShell`, positioned TOP|BOTTOM / LEFT|RIGHT.

**Comment by az01101001** [comment]
Sounds good! I'd love to take a stab at it. I assume the option to have a brightness slider in the `Controls` module would still be there for those who are only using a single display?

**Comment by nwg-piotr** [comment]
Of course. Let's leave Controls as is, and just add a new module.

**Comment by az01101001** [comment]
Alright, I'll work on it on a new branch

**Comment by az01101001** [comment]
@nwg-piotr, the [branch](https://github.com/az01101001/nwg-panel/tree/BrightnessSlider) works for now, but there are some things I want to discuss first.

As the `BrightnessSlider` module is a panel widget, I wanted to make the popup window with the slider appear directly next to the widget itself. But I was not able to achieve this with `GtkLayerShell`, so I opted to use `Gtk.Window` instead. Is there any disadvantage to this?

If using `GtkLayerShell`, here are some options I've considered:

1. Make the popup slider window fixed/anchored to the edge, similar to `openweather`.
2. Floating window-like (similar to how notification bubbles appear), and allow users to manually specify its x and y.
3. Use `Gtk.ScaleButton` or `Gtk.Popover`, so that the popup can easily appear relative to the widget (but the [popup arrow](https://python-gtk-3-tutorial.readthedocs.io/en/latest/popover.html#example) bothers me, and AFAIK it can only be removed in GTK4)

**Comment by nwg-piotr** [comment]
> Make the popup slider window fixed/anchored to the edge, similar to openweather.

Yes. Anchor it to the left / right / none edge horizontally and to top / bottom / none edge vertically. Let the user choose where they want it to show up. You could also allow to set vertical and horizontal margins.

**Comment by az01101001** [comment]
Made another PR #130. I am thinking of making another slider for volume, since the code will be pretty much the same.

**Comment by nwg-piotr** [comment]
> I am thinking of making another slider for volume

I'm not sure. It will double what we already have, and `config.py` is already big enough. What pros do you see?

**Comment by az01101001** [comment]
> What pros do you see?
Not much tbh, other than giving the option for users. I personally won't be using it either. Let's just leave it at that then, it should just be a quick fix if anyone wants it down the line.

**Comment by nwg-piotr** [comment]
Pay attention to the fact, that I also merged #131.

**Pull request merged**
