### PR TITLE
Implement launch filters

### PR DESCRIPTION
**Pull request by pol-rivero**
I recently installed hyprland on my laptop and realized that nwg-panel doesn't have any way to define screen "layouts". For example:
- If I have the laptop docked, I want to have one panel/bar on each display.
  - Example: Show panel A on display A and panel B on display B.
- When I unplug the external screens, I want to "move" some modules that were previously on the external displays "into" the bar in my laptop screen.
  - Example: Show panel C on display A. Panel C is similar to panel A, but has more modules.

The simplest way I found to allow this was to add some filters that determine if a panel will be launched, based on the displays that are currently connected.
I added 2 new panel settings:

- "Run if outputs exist": Comma-separated list of outputs which must **all** be connected in order for this panel to be launched.
  - Example: On panels A and B, add the condition that display B must be connected.

- "Run if outputs absent": Comma-separated list of outputs which must **all** be disconnected in order for this panel to be launched
  - Example: On panel C, add the condition that display B must be disconnected.

Since the two conditions can be combined and each allow a _list_ of displays, I think this system is flexible enough for complex situations. Perhaps in the future it could be extended to consider monitor names instead of output (port) names.

I placed the new settings next to the Output selector:
image

Feel free to change the presentation and translations (I used ChatGPT) as you see fit.

I've seen there is a setting called "Restart on display connected" which would work nicely with this filtering feature, but it doesn't seem to work on my end, and I currently need to manually relaunch nwg-panel when I plug or unplug a monitor. Tomorrow I will investigate and see if I discover why.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
I'll take a look as soon as I can.

**Comment by pol-rivero** [comment]
No worries, take as much time as you need.

I've taken a look at "Restart on display connected" and it seems that it's only implemented on sway (on_i3ipc_event). I'll try to implement a hyprland check when I have some time.

**Comment by nwg-piotr** [comment]
> it seems that it's only implemented on sway 

Yes, I don't remember doing this on Hyprland.

**Comment by pol-rivero** [comment]
I have added the missing "Restart on display connected" for Hyprland. It seemed suspiciously easy, so let me know any mistakes I may have made.
This PR is now ready for review. I'm especially interested in your opinion on how to best present this setting to the user, since my current solution (2 textboxes of comma-separated display names) doesn't seem all that intuitive.

**Review by nwg-piotr — CHANGES_REQUESTED** [review]
OK, let's leave it as is, apart from one change: as this feature does not support monitor names, but only output names, and it most probably won't be used by 99% of users, I'd like the fields "Run in output exists" and "Run i outputs absent" to go the the very bottom of the config form. It would be also not bad if you could add some info on the [Configuration](https://github.com/nwg-piotr/nwg-panel/wiki/Configuration) Wiki page.

**Comment by pol-rivero** [comment]
No problem. I've moved the new text fields to the bottom of the form and rebased the branch with the new commits from master.

**Pull request merged**
