### PR TITLE
Misc cleanups

### LINKED ISSUE #237: [BUG] Post two recent updates (...9.8/9.9) issues with panel displaying correctly
**Describe the bug**
Since I updated to 9.8 for the first time in a week or so yesterday via yay (and then 9.9 today) I'm having some issues not just with icons on the panel, but even with some of the controls modules. Those were working fine, but I did notice last week or the week before that whenever I launched the GUI editor, made changes, and hit "Apply/Restart" it appeared to restart the panel, but would come back up with no changes. If you went back to the GUI you'd see that the changes were never committed. As of the system updates that I ran yesterday for the volume and bluetooth controls inside that panel my icons are broken and no information displays. It just shows a circular arrow and if I manually toggle that from inside the controls drop down and it launches blueman it appears to remedy itself, but the volume does not and it doesn't look like the correct output is present in the output switcher. I tried to disable even showing the output switcher and re-enabling via the GUI and it doesn't appear to do anything.

**To Reproduce**
The *ONLY* way I can get it to work mostly correctly is by manually running nwg-panel from the terminal. Restarting Sway with Super+Shift+C does restart it, but it comes back broken again, even if it was running by manual command prior. My Sway config includes "exec_always nwg-panel" and I tried commenting that out and just using "exec nwg-panel" and get the same results. Many, many reboots, restarts of Sway, making sure everything is up to date (pacman and yay), reinstalling nwg-panel and nwg-panel-git, manually uninstalling all panel packages and downloading and installing 9.7, so on and so forth.

**Expected behavior**
nwg-panel launches just fine and shows the correct/mostly accurate (probably polling delay) data, and changes made in the recommended GUI should remain intact when hitting Apply/Refresh and rebooting/reloading Sway, etc.

**Screenshots**
What a chunk of the bar looks like when misbehaving:
image

Same spot when ran manually from terminal (looks good):
image

**Desktop (please complete the following information):**
 - Arch (up-to-date)
 - Sway version `sway -v': 1.8.1
 - Panel version `nwg-panel -v`: 0.9.9

**Additional context**
Everything should be up to date. Not sure why it started acting up. I have read where Python updates can sometime break stuff like this, so I reinstalled nwg-panel several times per some of the notes I saw, unless reinstalling Python itself was the recommendation, not just nwg-panel. Additional context:
Surface Pro 6
Arch/Sway
Most of the nwg- apps are installed
i5 / 8GB RAM / plenty of SSD capacity

THANK YOU!

PS - if I forgot/left out/didn't know how to provide some tidbit of information, please just let know and I'll do my best to fix it :)

### PR DESCRIPTION
**Pull request by MoetaYuko**
* Remove try-catch inside get_brightness, as there are already try-catch blocks when invoking it
* Removed the `bluetooth` module from controls to fix #237
* Removed the `net` module from controls

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Bluetooth and Web interface are no longer necessary, since we have the Tray module. I think they could be both deleted.

**Comment by MoetaYuko** [comment]
> Bluetooth and Web interface are no longer necessary, since we have the Tray module. I think they could be both deleted.

Done, plz double-check if there're leftovers.

**Comment by nwg-piotr** [comment]
"net" seems to have persisted in config.py, as well as in default config.

**Comment by MoetaYuko** [comment]
removed from default config, but didn't find occurrence in config.py

**Comment by nwg-piotr** [comment]
You're probably right. I must have confused something.

**Comment by nwg-piotr** [comment]
@MoetaYuko If you don't plan on further PRs in the nearest future, I can release tonight.

**Comment by MoetaYuko** [comment]
> @MoetaYuko If you don't plan on further PRs in the nearest future, I can release tonight.

No, I don't. Feel free to release it anytime.

**Comment by nwg-piotr** [comment]
OK, in 9-10 hours.

**Comment by nwg-piotr** [comment]
v0.9.10 released, AUR up to date.

> Once released, should I go back to the "normal" not -git version for any reason?

Yes, to receive further updates.

> but what am I missing that there's no bluetooth icon? Do I need an exec_always blueman or something in my config?

I don't use bluetooth often, so I turn it on with blueman-manager when needed. If I remember well, setting:

```
[Policy]
AutoEnable=true
```

in `/etc/bluetooth/main.conf` used to do the job in the past, but it doesn't work for me now for some reason.

**Comment by Brittle73** [comment]
@nwg-piotr @MoetaYuko thank you guys! I uninstalled -git and reinstalled the normal one and the primary issues that I wrote in for are resolved.

The only remaining thing that I can see is that something is up with the brightness indicator still. I have it disabled in the Controls section and instead liked how the module looked/felt independently, so I just have it in the right modules on the top bar. Using Light. My bindsym configs work fine, and I am now using SwayOSD which might be a contributing factor, but I feel like about the same time as the editor client started acting wonky the brightness percentage required a refresh of Sway and/or nwg-panel. If I do that it reflects an accurate value. The actual pop up slider does work and reflects immediately, but for some reason the panel is having a hard time updating the percentage on its own. I've always had the settings in the client on light and leaving the device blank (heeding your advice on the tooltip!). I did also just try and enter in the name of the device using the output of light -L and refreshed everything, same results. Is that something that could still be buggy, or did I do something wrong?

Thanks again!

**Pull request merged**
