### PR TITLE
Implement scroll events on workspace

### LINKED ISSUE #178: Missing features in workspaces
**Is your feature request related to a problem? Please describe.**

Trying to migrate from swaybar to nwg-panel and I am missing a few things

**Describe the solution you'd like**

- mouse scroll on workspace list should move to previous/next workspace
- when the panel is shown on all outputs, the workspace list should not contain the workspaces that do not belong to the current output

### PR DESCRIPTION
**Pull request by mildred**
Fix #178

### CODE REVIEW

**Comment by nwg-piotr** [comment]
I've just merged from another branch. Could you update your fork to the current `master`? This would make testing easier.

**Comment by mildred** [comment]
Thanks for looking at this. tell me if you prefer separate PRs for the different things.

**Comment by nwg-piotr** [comment]
> tell me if you prefer separate PRs for the different things

Yes, and well tested, please. Also please discuss major changes before you start working on them.

I'm working on further multi-lang support for nwg-shell. Will take a closer look at your PR before the nearest nwg-panel release (and merge if possible). Hopefully this weekend.

**Comment by nwg-piotr** [comment]
> - add a "hide-empty" configuration to hide empty workspaces

I don't see such a setting. Has it been implemented yet?

**Pull request merged**
