### PR TITLE
Shorten refresh delay so it isn't obvious

### PR DESCRIPTION
**Pull request by Outfoxxed**
More visually pleasing: workspace switch and playerctl changes appear to be instant now.

### CODE REVIEW

**Review by nwg-piotr — COMMENTED** [review]
The values you'd like to change are a compromise between responsiveness and CPU usage. On my old testing laptop the change in main.py increases CPU load twice (4% -> 8%). The change in playerctl.py keeps CPU load above 90%.

The delay in playerctl has another purpose as well: while playing music from a browser, with too frequent refreshes, you'll see the "stopped" status between tunes.

**Comment by simplejack-src** [comment]
A more proper solution to this issue would be to either spawn a process running 'playerctl --follow status' and process the notifications as they come (updating the UI). Or going to the source and blocking on the dbus ([MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/)) object.

**Comment by Outfoxxed** [comment]
Oh didn't realize that, thought I saw something about only redrawing when nessesary but I don't understand the codebase or python very well. Sorry.

**Comment by nwg-piotr** [comment]
I always keep the CPU load indicator in my bottom panel. :)

**Comment by nwg-piotr** [comment]
Closing due to reasons explained above.

**Pull request closed without merging**
