### PR TITLE
Refresh sway modules via event callbacks of i3ipc

### PR DESCRIPTION
**Pull request by MoetaYuko**
This nukes the overkill 200ms check_tree and solely relies on i3ipc events to trigger refreshing sway modules. In the future, we can do incremental updates based on IPC info to improve the responsibility further.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
In the meantime I rebuilt the Hyprland watcher and now we have a conflict. :/

**Comment by MoetaYuko** [comment]
rebased

**Comment by nwg-piotr** [comment]
All right, I'll launch it here to see what it looks like.

**Comment by nwg-piotr** [comment]
main.py lines 188 & 198 please rename to `common.h_workspaces_list`.

**Comment by nwg-piotr** [comment]
SwayWorkspaces: while moving focus between windows placed side by side on the same workspace, the task box doesn't get highlighted. The refresh method seems not to be called. Same applies to SwayTaskbar.

**Comment by MoetaYuko** [comment]
> SwayWorkspaces: while moving focus between windows placed side by side on the same workspace, the task box doesn't get highlighted. The refresh method seems not to be called. You might've not subscribed to some event.

What does the "task box" of SwayWorkspaces refer to? I'm only aware of the workspace label indicating the focused workspace, and it shouldn't change when you don't move focus to another workspace.

**Comment by nwg-piotr** [comment]
https://github.com/MoetaYuko/nwg-panel/blob/1aac2353580b17c1be1d72eeb20a3c0960ce695c/nwg_panel/modules/sway_workspaces.py#L180

**Comment by MoetaYuko** [comment]
> https://github.com/MoetaYuko/nwg-panel/blob/1aac2353580b17c1be1d72eeb20a3c0960ce695c/nwg_panel/modules/sway_workspaces.py#L180

Alright, it's also the "workspace label" I referred. It highlights fine for me even if the focused workspace does not have any windows.
> while moving focus between windows placed side by side on the same workspace, the task box doesn't get highlighted

This is weird, it highlights fine for me even if the focused workspace does not have any windows. Assume you have two windows A and B in workspace 1, the label "1" should be highlighted regardless of whether A or B is focused.

**Comment by nwg-piotr** [comment]
It should behave like this: https://youtu.be/qiRjZVil6D4

**Comment by MoetaYuko** [comment]
> It should behave like this: https://youtu.be/qiRjZVil6D4

Thanks for the video, but it's marked private and I can't watch xD

**Comment by nwg-piotr** [comment]
Sorry, check again.

**Comment by MoetaYuko** [comment]
> Sorry, check again.

Still can't

**Comment by nwg-piotr** [comment]
Now?

**Comment by MoetaYuko** [comment]
Can see the video but...my SwayWorkspaces module looks like this:
image
It shows workspace labels and the title/icon of focused window only

Sway-taskbar looks somewhat similar to the one in your video, but focused window is correctly highlighted

can you share the config to reproduce the video?

**Comment by nwg-piotr** [comment]
Shit, I wrote "Workspaces"? Sorry! I spent a couple of nights over HyprlandWorkspaces.

My config has nothing to do with the fact that the refresh method doesn't fire on moving the mouse pointer over windows in the same workspace.

**Comment by MoetaYuko** [comment]
If you meant sway taskbar, the refresh method does fire on window focus

https://user-images.githubusercontent.com/5774651/235362752-42a6309e-98a4-4aeb-95aa-9ca724b05b1c.mp4

**Comment by nwg-piotr** [comment]
It doesn't on what I cloned from your `i3event` branch, at least on my machine.

**Comment by MoetaYuko** [comment]
> It doesn't on what I cloned from your `i3event` branch, at least on my machine.

This is really weird. Just checked that my local commit HEAD is 1aac2353580b17c1be1d72eeb20a3c0960ce695c and same as the github version.

On the code side, the subscribed event is `Event.WINDOW`, which is a "catch-all" signal of all window events including focus. Can you add some prints to on_i3ipc_event of sway_taskbar.py to determine if it's triggered when moving focus?

**Comment by nwg-piotr** [comment]
```python
    def on_i3ipc_event(self, i3conn, event):
        print(event)
        GLib.idle_add(self.refresh,
                      i3conn.get_tree(),
                      priority=GLib.PRIORITY_HIGH)
```

When moving between outputs, it prints: `<i3ipc.events.WorkspaceEvent object at 0x7fe1c4742710>`. When moving over windows in the same workspace, it prints nothing.

**Comment by nwg-piotr** [comment]
I've just cloned your repo on my ancient testing lappy, and the `i3event` branch behaves exactly the same way.

**Comment by nwg-piotr** [comment]
Also: I have no idea when it was broken, as well as why it seems to work in your video, but custom labels in my SwayWorkspaces module don't work as expected:

image

I haven't noticed so far, as I haven't used custom labels for ages.

**Comment by MoetaYuko** [comment]
Rebased on master and it still works when moving over windows in the same workspace. Added print to on_i3ipc_event and I see both WorkspaceEvent and WindowEvent being triggered. No idea what could be wrong on your side :\

Do other modules that rely on WindowEvent work as expected? For example:
1. the window icon and title of SwayWorkspaces should change when moving over windows, as shown in the top left one in my video
2. the scratchpad module should show app icons after moving windows to the scratchpad

**Comment by nwg-piotr** [comment]
I've cloned and installed from your branch again. The SwayTaskbar module shows no changes until I change a workspace. Just opened window doesn't show up in it. The scratchpad indicator remains invisible, too. The SwayWorkspace module only refreshes when I point another workspace. Whatever relies on the WINDOW event - doesn't work.

My other machine runs just installed ArchLinux with nwg-shell, and it behaves the same way.

**Comment by MoetaYuko** [comment]
> I've cloned and installed from your branch again. The SwayTaskbar module shows no changes until I change a workspace. Just opened window doesn't show up in it. The scratchpad indicator remains invisible, too. The SwayWorkspace module only refreshes when I point another workspace. Whatever relies on the WINDOW event - doesn't work.
> 
> My other machine runs just installed ArchLinux with nwg-shell, and it behaves the same way.

Could you check if this simple script responds on window focus:
```python
from i3ipc import Connection, Event

i3 = Connection()


def on_window(i3, e):
    print(e)


i3.on(Event.WINDOW, on_window)
i3.main()
```

**Comment by nwg-piotr** [comment]
```txt
$ python3 winevent.py
<i3ipc.events.WindowEvent object at 0x7f00b6f9a830>
<i3ipc.events.WindowEvent object at 0x7f00b6f9a800>
<i3ipc.events.WindowEvent object at 0x7f00b6f9a890>
<i3ipc.events.WindowEvent object at 0x7f00b6f9a830>
<i3ipc.events.WindowEvent object at 0x7f00b6f9a800>
<i3ipc.events.WindowEvent object at 0x7f00b6f9a890>
<i3ipc.events.WindowEvent object at 0x7f00b6f9a830>
<i3ipc.events.WindowEvent object at 0x7f00b6f9a800>
<i3ipc.events.WindowEvent object at 0x7f00b6f9a890>
<i3ipc.events.WindowEvent object at 0x7f00b6f9a830>
<i3ipc.events.WindowEvent object at 0x7f00b6f9a800>
```

**Comment by MoetaYuko** [comment]
I have no idea what's going wrong after revisiting the changes. Could you debug it when you have time, or find me a way to reproduce your issue...

The first step is to check subscribed events and test the callback in main.py:
```diff
diff --git a/nwg_panel/main.py b/nwg_panel/main.py
index 8b12d4c..cf4ab7a 100644
--- a/nwg_panel/main.py
+++ b/nwg_panel/main.py
@@ -206,6 +206,7 @@ def hypr_watcher():
 
 
 def on_i3ipc_event(i3conn, event):
+    print(event)
     if isinstance(event, i3ipc.OutputEvent) and common_settings["restart-on-display"]:
         num = num_active_outputs(i3conn.get_outputs())
         if num > common.outputs_num:
@@ -800,6 +801,8 @@ def main():
         # be executed there. Hence, UI operations MUST be scheduled by
         # Gdk.threads_add_*() or their GLib counterpart to make them happen in
         # Gtk's main loop.
+        from i3ipc._private.types import EventType
+        assert common.i3.subscriptions == (EventType.WORKSPACE.value | EventType.OUTPUT.value | EventType.WINDOW.value)
         thread = threading.Thread(target=common.i3.main, daemon=True)
         thread.start()

```
If still no response on window focus, the next is to check the raw data from the socket, you can add a print here https://github.com/altdesktop/i3ipc-python/blob/9de8e885536bf611c96cc7c8ea0b2f19dd40f4f2/i3ipc/connection.py#L494

**Comment by nwg-piotr** [comment]
OK. I'm working today, so it must wait till the evening.

**Comment by nwg-piotr** [comment]
connection.py

```python
        data = json.loads(data)
        msg_type = 1 << (msg_type & 0x7f)
        event_name = ''
        event = None
        if msg_type == EventType.WORKSPACE.value:
            event_name = 'workspace'
            event = WorkspaceEvent(data, self)
        elif msg_type == EventType.OUTPUT.value:
            event_name = 'output'
            event = OutputEvent(data)
        elif msg_type == EventType.MODE.value:
            event_name = 'mode'
            event = ModeEvent(data)
        elif msg_type == EventType.WINDOW.value:
            event_name = 'window'
            event = WindowEvent(data, self)
        elif msg_type == EventType.BARCONFIG_UPDATE.value:
            event_name = 'barconfig_update'
            event = BarconfigUpdateEvent(data)
        elif msg_type == EventType.BINDING.value:
            event_name = 'binding'
            event = BindingEvent(data)
        elif msg_type == EventType.SHUTDOWN.value:
            event_name = 'shutdown'
            event = ShutdownEvent(data)
        elif msg_type == EventType.TICK.value:
            event_name = 'tick'
            event = TickEvent(data)
        elif msg_type == EventType.INPUT.value:
            event_name = 'input'
            event = InputEvent(data)
        else:
            # we have not implemented this event
            return
        print(event_name)
```

This only prints 'workspace' for me.

**Comment by nwg-piotr** [comment]
Yeah, I supposed the difference was on your side, as it fails working on my both machines the same way.

**Comment by MoetaYuko** [comment]
I know why, OutputEvent support is added recently https://github.com/swaywm/sway/commit/40eb29e7c56b67c2112ead7f048e45220a1c2887, listening to it on an unsupported version breaks WindowEvent

Fortunately, it turns out that both WindowEvent and WorkspaceEvent get fired on output change, so we can rely on them to detect new outputs.

**Comment by MoetaYuko** [comment]
Should be working now

**Comment by nwg-piotr** [comment]
I have a spare half an hour, even if it's not yet night in my place. ;) Will try and tell you.

**Comment by nwg-piotr** [comment]
Seems to work all right. I'll test it better tonight. Is it ready to merge yet, provided that I find no further issues?

**Comment by MoetaYuko** [comment]
Done

**Comment by nwg-piotr** [comment]
Thanks!

**Pull request merged**
