### PR TITLE
Properly arrange the alpha channel for IconPixmap

### PR DESCRIPTION
**Pull request by MoetaYuko**
Before:
image

After:
image

### CODE REVIEW

**Comment by MoetaYuko** [comment]
I have a 4k monitor w/ scaling factor 2 and a 1080p one w/o scaling. Before this commit, the icon looks like *Before* on both of them. After this commit, it looks like *After* on my 4k monitor, but not good on the 1080p one:
image
this is weird and needs further investigation.

**Comment by nwg-piotr** [comment]
Take your time. What I'm currently working on, only changes main.py, modules/hyprland_taskbar.py, and adds modules/hyprland_workspaces.py.

**Comment by MoetaYuko** [comment]
now working as expected

**Comment by nwg-piotr** [comment]
OK

**Pull request merged**
