### PR TITLE
Update widget CSS to name parent object.

### PR DESCRIPTION
**Pull request by simplejack-src**
This allows easier selection of child elements.

### CODE REVIEW

**Review by nwg-piotr — COMMENTED** [review]
Well, I'm not sure. For current users it's going to be a braking change, isn't it? Their current css sheets would be broken. I'll take a closer look at it tonight.

**Comment by simplejack-src** [comment]
@nwg-piotr There's a decent chance of that true (if anyone is making references to these elements in their CSS, with this change the rules will now apply to the parent object). How about I make a different change to leave the CSS name on the current element (the way it is now) and name the parent object (for those that it's not) to something like 'root-object' ? This way I can still select CSS elements in a top-down way but no one will see any change from how its currently styled.

i.e. For an executor, it's settings["css-name"] would still refer to it's label, but it's parent object (the EventBox) would be named ("root-" + settings["css-name"])

**Comment by nwg-piotr** [comment]
Sounds good to me. Do your job, and I'll look into it later tonight.

**Comment by simplejack-src** [comment]
Closed in favor of #57 (a non-breaking change).

**Pull request closed without merging**
