### PR TITLE
set sliders' increment to 0.5, 0.5

### PR DESCRIPTION
**Pull request by nwg-piotr**
requested here: https://github.com/nwg-piotr/nwg-shell/discussions/417

### CODE REVIEW

**Comment by ricostap** [comment]
Wow, thank you for doing this and so fast.  I really appreciate it.

I am a newbie when it comes to linux and git hub so please excuse my next question. What do I have to do now? Clone the repository and run the install script again?

**Comment by nwg-piotr** [comment]
Just wait a little bit. I haven't yet released it, as nwg-panel had 4 or 5 consequent releases in last few days, and I didn't want to infuriate packagers. I'll take a look at #331 tonight and release a new version having it done.

**Comment by ricostap** [comment]
Perfect, thank you. I can wait.
I am a regular user who likes to tinker and my native language is German. If there is anything I can help with the project please feel free to let me know.

**Comment by ricostap** [comment]
Does that look about right?

image

**Comment by nwg-piotr** [comment]
I'd be grateful. They taught me German for 6 years, but with poor results. :D

**Comment by ricostap** [comment]
Hi Piotr,

Attached please find a partially finished file. First time I am doing this so I hope I get the terms right. Anyway, when I open the file in the translation screen, it does not populate the fields which are already translated and shows all fields as empty. I'll just start a new file for now and send it in increments.
[nwg_shell_config-de_DE.json](https://github.com/user-attachments/files/17500584/nwg_shell_config-de_DE.json)

**Comment by nwg-piotr** [comment]
> when I open the file in the translation screen, it does not populate the fields which are already translated and shows all fields as empty

This is a bug, and I already have a fix, however I need to test it a bit more. Hold off on further translation until a new version of nwg-shell-config is released. This will save you a lot of time.

**Comment by nwg-piotr** [comment]
I've just [released](https://github.com/nwg-piotr/nwg-shell-config/releases/tag/v0.5.49) v0.5.49.

**Comment by ricostap** [comment]
seems to be working well now :)

**Pull request merged**
