### PR TITLE
Brightness slider

### PR DESCRIPTION
**Pull request by az01101001**
I didn't implement `ddcutil` here because I thought it'd be better practice to keep them in separate forks? I will just do another rebase later.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
`ddcutil` is the only reason to have a separate brightness slider, if you want my opinion.

**Comment by az01101001** [comment]
Wait did you mean `BrightnessSlider` is **just for** `ddcutil`?
While `Controls` will **only have** `light` and `brightnessctl`?

**Comment by nwg-piotr** [comment]
`ddcutil` in Controls makes no sense, due to the high CPU usage with numerous instances of the module. If you want, it may be left there, but I wouldn't recommend anyone to use another Controls module instance on each display.

If it comes to the slider, it's up to you, but the only added value I see is `ddcutil` support.

**Comment by az01101001** [comment]
> If you want, it may be left there, but I wouldn't recommend anyone to use another Controls module on each display.

Yeah, it'd be nice to have the option for `ddcutil` in `Controls`, for those on desktop with single monitor setups (i.e. me lol).

> If it comes to the slider, it's up to you, but the only added value I see is ddcutil support.

`BrightnessSlider` currently only has `light` and `brightnessctl` (no `ddcutil` yet). I was thinking on implementing `ddcutil` here by rebasing this branch later.

**Comment by nwg-piotr** [comment]
> for those on desktop with single monitor setups

Very well. I'll be able to use it too, on my only desktop machine at the office.

>  I was thinking on implementing ddcutil here by rebasing this branch later.

I see it as a key feature of this module. We're not in hurry. We'll be ready when we're ready.

**Comment by az01101001** [comment]
> Very well. I'll be able to use it too, on my only desktop machine at the office.

Awesome!

> I see it as a key feature of this module. We're not in hurry. We'll be ready when we're ready.

Alright, I'll do a rebase here once #119 has been merged. But yeah I agree no need to rush. I'm logging out soon anyways since its nighttime here.

**Comment by az01101001** [comment]
Done!

**Comment by nwg-piotr** [comment]
Let me take a look.

**Comment by nwg-piotr** [comment]
https://github.com/az01101001/nwg-panel/blob/2f496bba965147756d2f63e14bd062c668167424/nwg_panel/config.py#L525

Please add BrightnessSlider to `self.known_modules`.

**Comment by az01101001** [comment]
Added!

**Comment by nwg-piotr** [comment]
Was it necessary to force the window size? Couldn't it just wrap the slider? I'm not sure, need to take a closer look at the code. What I mean is: after changing the slider orientation, it remains useless until I redefine its width and height.

**Comment by az01101001** [comment]
If II don't specify the window size, it just takes the smallest shape it can get. It's like, the slider follows and expands according to the window size, rather than the other way around. I was debating on just using a single `popup-length` that automatically sets width when horizontal or height when vertical, but ultimately decided to leave it up to the user.

**Comment by nwg-piotr** [comment]
Alright, let it stay as is. Let me leave it in testing for a day before merging.

BTW: one of my external displays misbehaves. The value in the slider resets to 0, even if the actual brightness seems not to change. Do you by any chance have a solution?

**Comment by az01101001** [comment]
I know that not all monitors are supported by ddcutil (like my old monitor). Have you tried inputting the cmd to the terminal?

**Comment by nwg-piotr** [comment]
Full command gives me errors 9 in 10 attempts, but just ` ddcutil getvcp 10 --bus=4` behaves well.

**Comment by az01101001** [comment]
I use `--sleep-multiplier=.01` and `--noverify` to speed up the command for my monitor, but maybe it depends on the monitor :/

> Why don't we check brightness this way?

Yeap thats probably best

Does the `setvcp` command work on your monitors with `--sleep-multiplier=.01` and `--noverify`? Maybe its better to remove them as well if it's gonna cause issues.

**Comment by nwg-piotr** [comment]
Fails on bus 4, works on 5. Same as `getcvp`. We should either remove these arguments, or make them optional in settings, turned off by default.

**Comment by az01101001** [comment]
Yeah I guess it really depends on the monitor then. Giving the option to choose is gonna make the settings even more bloated, especially since the options are not gonna be relevant for the other brightness controllers. How do you find the speed/responsiveness on your monitors?

**Comment by nwg-piotr** [comment]
> Giving the option to choose is gonna make the settings even more bloated

Very true.

> How do you find the speed/responsiveness on your monitors?

Butter fluent w/o those arguments.

**Comment by nwg-piotr** [comment]
Oh, shouldn't we add mutable refresh rate, as in other modules? 5 s is quite a long time.

**Comment by az01101001** [comment]
> Butter fluent w/o those arguments.

Its the opposite for mine hahah.

> The returned brightness value takes time to refresh.

The refresh takes time for me as well, even with the extra arguments.

Better to just remove them then, in the interest of reliability. Maybe give a warning to users that it might not behave as expected depending on their monitor.

**Comment by az01101001** [comment]
> ~Oh, shouldn't we add mutable refresh rate, as in other modules? 5 s is quite a long time.~ Stupid me.

RIP I forgot to change it to `settings["interval"]` during testing...

**Comment by nwg-piotr** [comment]
Haha! Just do it!

**Comment by az01101001** [comment]
Is it alright if I just make the changes to `getvcp` and `setvcp` in this branch?

**Comment by nwg-piotr** [comment]
One minor thing: for the "Brightness slider" item in the config menu template, please `set_selectable[False]`.

**Comment by nwg-piotr** [comment]
Sliders are less responsive now, indeed. But both work.

**Comment by az01101001** [comment]
Is [that](https://github.com/nwg-piotr/nwg-panel/pull/130/commits/da8170f8c0e04c4ae97ecde1729783fb8ca7534e) what you meant?

**Comment by nwg-piotr** [comment]
Yes. Just like all the other list items.

**Comment by az01101001** [comment]
> Sliders are less responsive now, indeed. But both work.

Yeap its a bit slower, but its not a big deal. The widget also seems to refresh more reliably now for mine.

**Comment by nwg-piotr** [comment]
I wonder if we could improve the scale responsiveness by connecting a signal other than `value-changed`. May be worth of try, but it's already 4 am in my place.

**Comment by az01101001** [comment]
I can try messing around with it

**Comment by nwg-piotr** [comment]
Possible solution to slider lags would be not to set brightness on every `value-changed`, but only to remember that the slider has been moved, and then apply the final value `on-button-release`.

https://gist.github.com/nwg-piotr/a0dfb9718865462b1d5fae953384201e

**Comment by az01101001** [comment]
Nice! I managed to reach the same conclusion, but was scratching my head trying to come up with a good solution. Your method makes sense to me, will try to test it on my end and report back some time tomorrow (in 12hrs-ish)

**Comment by nwg-piotr** [comment]
Very well. Same could be back-ported to the Controls module.

**Comment by nwg-piotr** [comment]
Actually, we only need it to work like this with ddcutil. So it should be like this:

```python
        if self.settings["backlight-controller"] == "ddcutil":
            self.bri_scale_handler = self.bri_scale.connect("value-changed", self.set_value_changed)
        else:
            self.bri_scale_handler = self.bri_scale.connect("value-changed", self.set_bri)
```

**Comment by az01101001** [comment]
Can confirm it works like a charm. I've also added the code for scroll-events on top of it. Do you mind if I just push them together here?

**Comment by nwg-piotr** [comment]
Sure!

**Comment by az01101001** [comment]
Thanks! Can you also help to test if the scroll-events work on laptop (non-ddcutil) because I cant :(

**Comment by nwg-piotr** [comment]
> Can you also help to test if the scroll-events work on laptop (non-ddcutil) because I cant 

No sooner than in 4 hours. 4 am here, and I need to get some sleep.

Are you interested in further development of this module?

Issue: When the slider works with ddcutils, the osd panel on the monitor gets closed every time ddcutil is called. This is quite a serious inconvenience. To resolve it, I propose:

- give up up vertical slider orientation;
- add the contrast slider below the brightness slider;
- add the color preset combo (`Feature 14`) below sliders;
- add a check button on the very bottom, to temporarily disable ddcutil calls when the user wants to access their osd panel.

What do you think? Of course I can take care of the code, but wanted to ask you first.

**Comment by az01101001** [comment]
> No sooner than in 4 hours. 4 am here, and I need to get some sleep.

Of course! No rush!

> Are you interested in further development of this module?

Oh that'd be great. I could use the practice. So basically try to re-create the OSD panel, right?

**Comment by nwg-piotr** [comment]
Because gtk.comboboxtext is horizontal, and will look stupid next to vertical sliders.

**Comment by az01101001** [comment]
Oh yeah you're right lol. Sure I think it's doable for me

**Comment by nwg-piotr** [comment]
Do you want me, for the record, to merge this branch now?

**Comment by az01101001** [comment]
Yeah that'd probably be best. Just in case I mess something up or cannot get it to work :p

I also just remembered to fix the slider in `Controls` as well

**Comment by az01101001** [comment]
Hmm I'm not having that issue. Maybe the last commit fixed it hahah

**Comment by nwg-piotr** [comment]
I'll check again as soon as I have a spare minute.

**Comment by nwg-piotr** [comment]
1. After restarting panel (reloading sway) the slider in just opened Controls popup indicates 0.  
2. Changing brightness elsewhere does not move the sliders in Conntrols.

image

**Comment by nwg-piotr** [comment]
I've got 45 spare minute at the office. Will clone and test.

**Comment by nwg-piotr** [comment]
Depends on the machine. On my old testing laptop with one external display, 3 panels, it's about 4%. Seems not more than it used to be.

**Pull request merged**
