### PR TITLE
fix tray icons for electron (#224)

### LINKED ISSUE #224: [BUG] Discord tray icon stopped working after sytem update
**Describe the bug**
The Discord tray icon stopped showing on my system after a system update, while others still work. I mainly use the Discord flatpak, but I tried installing the discord AUR package, as well as the Webcord flatpak, and all of them have the same issue.

`journalctl` shows an error as follows:

```
May 17 10:40:46 XXXX sway[1436]: time="2023-05-17T10:40:46+08:00" level=info msg="env vars: [--branch=stable --arch=x86_64 --command=discord]; command: '/usr/bin/flatpak'; args: [run --branch=stable --arch=x86_64 --command=discord com.discordapp.Discord]\n"
May 17 10:40:46 XXXX systemd[658]: Started app-flatpak-com.discordapp.Discord-8957.scope.
May 17 10:40:46 XXXX systemd[658]: Started app-flatpak-com.discordapp.Discord-8997.scope.
May 17 10:40:47 XXXX sway[9047]: The XKEYBOARD keymap compiler (xkbcomp) reports:
May 17 10:40:47 XXXX sway[9047]: > Warning:          Unsupported maximum keycode 708, clipping.
May 17 10:40:47 XXXX sway[9047]: >                   X11 cannot support keycodes above 255.
May 17 10:40:47 XXXX sway[9047]: Errors from xkbcomp are not fatal to the X server
May 17 10:40:47 XXXX sway[1438]: Traceback (most recent call last):
May 17 10:40:47 XXXX sway[1438]:   File "/usr/lib/python3.11/site-packages/dasbus/client/observer.py", line 88, in _name_appeared_callback
May 17 10:40:47 XXXX sway[1438]:     callback(name_owner, *callback_args)
May 17 10:40:47 XXXX sway[1438]:   File "/usr/lib/python3.11/site-packages/dasbus/client/observer.py", line 230, in _service_name_appeared_callback
May 17 10:40:47 XXXX sway[1438]:     self._enable_service()
May 17 10:40:47 XXXX sway[1438]:   File "/usr/lib/python3.11/site-packages/dasbus/client/observer.py", line 220, in _enable_service
May 17 10:40:47 XXXX sway[1438]:     self._service_available.emit(self)
May 17 10:40:47 XXXX sway[1438]:   File "/usr/lib/python3.11/site-packages/dasbus/signal.py", line 53, in emit
May 17 10:40:47 XXXX sway[1438]:     callback(*args, **kwargs)
May 17 10:40:47 XXXX sway[1438]:   File "/usr/lib/python3.11/site-packages/nwg_panel/modules/sni_system_tray/item.py", line 63, in item_available_handler
May 17 10:40:47 XXXX sway[1438]:     self.item_proxy.NewTitle.connect(
May 17 10:40:47 XXXX sway[1438]:     ^^^^^^^^^^^^^^^^^^^^^^^^
May 17 10:40:47 XXXX sway[1438]:   File "/usr/lib/python3.11/site-packages/dasbus/client/proxy.py", line 161, in __getattr__
May 17 10:40:47 XXXX sway[1438]:     member = self._get_member(self._get_interface(name), name)
May 17 10:40:47 XXXX sway[1438]:                               ^^^^^^^^^^^^^^^^^^^^^^^^^
May 17 10:40:47 XXXX sway[1438]:   File "/usr/lib/python3.11/site-packages/dasbus/client/proxy.py", line 223, in _get_interface
May 17 10:40:47 XXXX sway[1438]:     raise AttributeError(
May 17 10:40:47 XXXX sway[1438]: AttributeError: DBus object has no attribute 'NewTitle'.
```

**To Reproduce**
1. Launch Discord.

**Expected behavior**
All system tray icons should work.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Arch Linux 6.3.1-arch1-1
 - sway version 1.8.1
 - nwg-panel version 0.9.2

**Additional context**
My suspicions is that it might have something to do with Arch updating to Python 3.11 from 3.10, where AUR packages that depends on Python break, and which before that the Discord tray icon still worked. I've rebuilt all my AUR packages that use Python (including python-dasbus) and all other system tray icons work from what I've tested so far, so I'm not sure why Discord specifically is having problems.

### PR DESCRIPTION
**Pull request by progandy**
Electron does not offer introspection data. This add the interface specification manually to allow dasbus to read the properties anyways.

Should fix #224 

Simple test for electron.

`electron index.js`

```javascript
const { app, BrowserWindow, Tray, Menu, nativeImage } = require('electron');
const path = require('path');

let mainWindow;
let tray = null;

app.setAppUserModelId('your.app.id');

app.whenReady().then(() => {
  mainWindow = new BrowserWindow({ width: 800, height: 600, show: false});

    tray = new Tray(nativeImage.createFromDataURL('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2P4v5ThPwAG7wKklwQ/bwAAAABJRU5ErkJggg=='));

  const contextMenu = Menu.buildFromTemplate([
    { label: 'Quit', click: () => app.quit() }
  ]);

  tray.setContextMenu(contextMenu);
  tray.setToolTip('Test tooltip');

  tray.on('click', () => {
    mainWindow.isVisible() ? mainWindow.hide() : mainWindow.show();
  });

});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
```

### CODE REVIEW

**Comment by nwg-piotr** [comment]
I tested briefly with the Discord app, and it worked well. Thank you!

**Comment by nwg-piotr** [comment]
Well, it works for me when running from PyCharm, bot not when installed. I must be doing something wrong.

**Comment by progandy** [comment]
I think I forgot to add the xml file to the package_data.

**Comment by nwg-piotr** [comment]
I was just thinking about it.

**Comment by nwg-piotr** [comment]
Fixed. Thank you one more time!

**Pull request merged**
