### PR TITLE
Name root/parent module GTK objects.

### PR DESCRIPTION
**Pull request by simplejack-src**
This allows the modules root object (the module object directly inheriting a GTK object) to be referenced in CSS (as 'root-' and whatever CSS name was configured for that module).

### CODE REVIEW

**Review by nwg-piotr — CHANGES_REQUESTED** [review]
1. nwg_panel/modules/controls.py

The Controls class derives from Gtk.EventBox. The line

```python
check_key(settings, "css-name", "controls-label")
```

seems to have remained there by oblivion. It seems that naming Gtk.EventBox "controls-label" makes little sense.

2. Nobody's going to learn about the new names, unless they appear in config GUI. Would you mind adding aproppriate fields in glade files, and their support in `config.py`?

**Comment by simplejack-src** [comment]
1 . 'controls-label' was just the name already set in 'css-name' (granted it's subsequently overwritten in the Popup part, aside from never actually being set). Following point 2 I suppose I can look to add a second 'css-name' ('css-overview' ?) for this particular module (seeing as the Controls module actually has two main GTK parts, the icons overview and the Popup itself).

2. Sure I'll have a look into that section and the Glade bit.

**Comment by nwg-piotr** [comment]
All right then. I tried to work on three various programs tonight, which won't result in anything good for sure. I fixed a bug in nwg-drawer, reviewed your PR, while still thinking about adding a feature to nwg-wrapper. I'll focus on the latter for now.

**Comment by simplejack-src** [comment]
A 'Root CSS' settings value has been added to refer to the base/root object in modules 'executor', 'controls' and 'clock' (which all currently set the base CSS name to a different element). Adding this as a new setting preserved backwards compatibility (i.e. no ones style is going to be changed unless they opt-in to setting and using these selectors)

**Review by nwg-piotr — APPROVED** [review]
Seems to be OK. What I don't like is that the configufation gradually gets more and more difficult to ordinary users. But it's not your fault, of course.

**Comment by nwg-piotr** [comment]
Haven't noticed at first: CSS names for executors disappeared, and I needed to add them again. Alright, let it stay as it is.

**Comment by simplejack-src** [comment]
> Seems to be OK. What I don't like is that the configuration gradually gets more and more difficult to ordinary users. But it's not your fault, of course.

Not sure what could be done to make that easier. Maybe a GUI re-jig (less explicit fields, maybe drop a number of them into separate combo-boxes? i.e. Add Action: Scroll Up, Left Click, etc.), however that would add a decent amount of complexity. Could also go the GNOME route and drop some options from the GUI but document them to be configurable in the configuration file (i.e.Hide the options).



> Haven't noticed at first: CSS names for executors disappeared, and I needed to add them again. Alright, let it stay as it is.

Disappeared? I assume you mean they weren't read from the configuration file into the GUI? That's strange, I didn't encounter this, and I'm not sure what would cause this... Best as I can tell the changes were all additive.

Thanks for the merge. I don't think I have anything else to change for my workflow (I just needed this change so I can have nice hover shadows around the modules I'm selecting).

**Comment by nwg-piotr** [comment]
Well, it's always better than to deal with json directly.

Could the release wait a few days? I'd like to integrate a plugin, but I need a weekend and some beer to deal with it.

**Comment by simplejack-src** [comment]
By all means (I'm just building from master anyway).

**Pull request merged**
