### PR TITLE
Event-driven playerctl

### PR DESCRIPTION
**Pull request by MoetaYuko**

### CODE REVIEW

**Comment by nwg-piotr** [comment]
```text
Traceback (most recent call last):
  File "/home/piotr/PycharmProjects/nwg-panel/nwg_panel/main.py", line 820, in <module>
    sys.exit(main())
  File "/home/piotr/PycharmProjects/nwg-panel/nwg_panel/main.py", line 789, in main
    common.outputs_num = num_active_outputs(common.i3.get_outputs())
  File "/home/piotr/PycharmProjects/nwg-panel/nwg_panel/tools.py", line 255, in num_active_outputs
    if item.type == "output" and not item.name.startswith("__"):
AttributeError: 'OutputReply' object has no attribute 'type'
```

**Comment by MoetaYuko** [comment]
ig sth wrong with your code? num_active_outputs definition and callers are changed in https://github.com/nwg-piotr/nwg-panel/commit/bef9d4007850f50f9f8d1f518745131432dc264d, but it turns out that you were using new main.py + old tools.py

**Comment by nwg-piotr** [comment]
I applied your changes to the current `master`. I might've done something wrong, though I don't thinks so. Will try again when I'm back home. Are you sure your branch is up to date with `master`?

**Comment by MoetaYuko** [comment]
The PR is not yet rebased but applies cleanly on master. You can cherry-pick the changes, or use `git pull origin pull/216/head --ff` on top of master.

**Comment by nwg-piotr** [comment]
Yes, seem to be all right.

**Pull request merged**
