### PR TITLE
fix: Remove executable bit from SVG icons

### PR DESCRIPTION
**Pull request by tim77**

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Interesting. No idea how it could have happened.

**Comment by tim77** [comment]
Trying to package it for Fedora repos. Not a bit deal but still could useful https://bugzilla.redhat.com/show_bug.cgi?id=1946547.

**Comment by nwg-piotr** [comment]
Thanks for pointing this out. And of course for packaging.

**Comment by nwg-piotr** [comment]
I know nothing on Fedora. Do you need a new release?

**Comment by tim77** [comment]
It's fine and i applied this minor patch. No need to worry about this minor issue IMO.

**Comment by nwg-piotr** [comment]
Alright. The panel will wait for its turn, if so, as I'm thinking in golang currently. ;)

**Comment by tim77** [comment]
Uh, that's much harder to package usually. :) Not always hard for sure. And not really harder, more time consuming probably, but this is more Fedora-related i would say.

**Comment by nwg-piotr** [comment]
I've never ever packaged Go, and dunno where even to start. For now I only use Makefile.

**Pull request merged**
